blank_issues_enabled: false
contact_links:
  - name: セキュリティアドバイザリ(repo2 リポジトリ)
    url: https://github.com/AlesInfiny/maris/security/advisories/new
    about: セキュリティ関連の問題、脆弱性の報告はセキュリティアドバイザリのフォームからお願いします。
